version: "3.6"

services:
  #PHP Service
  hb_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    image: txzy/hb_app:1.1.0
    container_name: hb_service_app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
      TZ: ${TIME_ZONE}
    working_dir: /var/www/
    volumes:
      - ./www/hb/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hb_net

  # Сервис для установки прав
  hb_permissions:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: hb_service_permissions
    restart: "no"
    user: root
    volumes:
      - ./www:/var/www
      - ./startup.sh:/startup.sh
    entrypoint: ["/bin/sh", "/startup.sh"]

  #Nginx Service
  hb_webserver:
    image: nginx:alpine
    container_name: hb_service_webserver
    restart: always
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      # - "5443:443"
    volumes:
      - ./www/hb/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/ssl/:/etc/nginx/ssl
      - ./nginx/conf/:/etc/nginx/conf
    entrypoint: ["/bin/sh", "/etc/nginx/conf/entrypoint.sh"]
    networks:
      - hb_net

#Docker Networks
networks:
  hb_net:
    driver: bridge
    # external: true
