server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel_debug
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel_debug
          log_type: debug
          __path__: /var/www/storage/logs/**/debug-*.log  # Для файлов типа debug-2025-05-15.log

  - job_name: laravel_tokens
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel_tokens
          log_type: tokens
          __path__: /var/www/storage/logs/**/tokens-*.log  # Для файлов типа tokens-2025-05-15.log

  - job_name: laravel_telegram
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel_tg
          log_type: telegram
          __path__: /var/www/storage/logs/**/telegramLogging-*  # Для файлов без расширения

  - job_name: laravel_general
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel_errors
          log_type: general
          __path__: /var/www/storage/logs/**/laravel-*.log  # Если есть общие логи

  - job_name: laravel_unknown
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel_unknown
          log_type: general
          __path__: /var/www/storage/logs/**/unknown-*.log  # Если есть общие логи

